### ISSUE TITLE
how to make changes with eosio-toppings  

### ISSUE THREAD

**Issue by awaissakhi11** [EOSIO/eosio-toppings#111]
i am developing eosio-explorer with my network and i am using eosio-explorer from github when i am changes in eosio-toppings its not reflecting on eosio-explorer

**Comment by terrylks** [comment]
Short explanation 
The `eosio-toppings` dependency in your local `eosio-explorer` is still pulled from npm registry. If you want to make changes on your local `eosio-toppings` to reflect on your local `eosio-explorer`, you need to do `yarn link` to replace the dependency to the local one.

Please take a look of this doc in eosio-explorer repo.
https://github.com/EOSIO/eosio-explorer/blob/master/docs/development.md

**Comment by terrylks** [comment]
Also, please make sure you run `tsc` to transpile ts to js after you change to typescript file in `eosio-toppings` in your local.

**Comment by awaissakhi11** [comment]
hello sir i update eos repository  to my edit code repository   but still its connected to eos main repository

**Comment by awaissakhi11** [comment]
( run tsc to transpile ts to js after you updated typescript files in eosio-toppings in your local.) how to do this is there any tutorial for this?

**Comment by terrylks** [comment]
@awaissakhi11 Have you tried `yarn link`? You must need `yarn link` to link your local `eosio-explorer` repo to local `eosio-toppings`

and

For tsc, please see the **compile and watch** section of
https://github.com/EOSIO/eosio-toppings/blob/master/packages/api-rpc/README.md

**Comment by awaissakhi11** [comment]
yes i tried yarn link i went to each folder then did yarn link i did changing after yarn link in docker-eosio-nodeos folder change the address docker file and init_blockchain as well but still on explorer its showing EOS on explorer

**Comment by terrylks** [comment]
First, how do you start your `eosio-explorer` in your local?

If you want to develop on `eosio-explorer` ( as well as develop on `eosio-toppings` ), you need to 
1. git clone the `eosio-explorer` and `eosio-toppings` repo.
2. you must start the explorer with `yarn eosio-explorer init` ( NOT `eosio-explorer init` <- it runs the global installed one )
3. start dev by `yarn eosio-explorer start -dev` ( so the explorer will run in port 3000 by default )
4. For yarn link, you need to do `yarn link` in toppings to declare the link, and do e.g. `yarn link @eosio-toppings/api-rpc` ( all eosio-toppings dependencies )in your local `eosio-explorer` repo.

If it still does not help. Could you provide me more information to let me understand your current situation more?

1. Which changes you are going to make on toppings? which packages?
2. Which changes you are going to make on explorer?
3. May be you could provide some cap screens?

**Comment by awaissakhi11** [comment]
hello sir 
ill tell how what i am doing 
1:first installing topping and cd into packages folder and chnage only /docker-eosio-nodeos folder and then run yarn link into each packages folder 
then i came to main directory like in eosio-topping folder then installing yarn installing

2: then cloning eosio-explorer then run 
yarn link @eosio-toppings/api-eosio-compiler
yarn link @eosio-toppings/api-mongodb-plugin
yarn link @eosio-toppings/api-rpc
yarn link @eosio-toppings/docker-eosio-nodeos
yarn link @eosio-toppings/docker-mongodb

and then run yarn install 
and then 
yarn eosio-explorer init 
then i am getting your setup in online and when i check brower with my ip xxxxxxx.5111 i can there the eos is running 

and thank you give response to me

**Comment by terrylks** [comment]
do you mean that you have solved the problem?

If not, what you are going to change in `docker-eosio-nodeos folder`?

**Comment by awaissakhi11** [comment]
in docker-eosio-nodeos folder i put my network data like my address with my prefix and with my network genesis when i am trying to run then eosio-explorer its running EOS network not mine

**Comment by terrylks** [comment]
What means by "network data like my address".
I think you need to provide in a more detail way to let us help on your project.

If it is a local working nodeos just for your local development, which network data you are going to modify?

**Comment by varshajnagaraja** [comment]
Closing the issue as no further question was asked
